In [1]:
import pandas as pd
import numpy as np

In [2]:
s1=pd.read_csv("stroke.csv")

In [4]:
s1.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [19]:
s2=s1.copy()

In [22]:
bmi_df=pd.DataFrame(s2['bmi'])

In [25]:
bmi_df_fil=bmi_df.fillna(bmi_df.mean())

In [36]:
dict1={'bmi':'bmi_m'}

In [37]:
bmi_df_fil.rename(columns=dict1, inplace=True)

In [45]:
s3=s2.drop('bmi', axis=1)

In [48]:
s4=s3.join(bmi_df_fil)

In [53]:
s4.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,smoking_status,stroke,bmi_m
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,formerly smoked,1,36.600000
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,never smoked,1,28.893237
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,never smoked,1,32.500000
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,smokes,1,34.400000
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,never smoked,1,24.000000

In [55]:
s5=pd.get_dummies(s4,['gender','ever_married','work_type','Residence_type','smoking_status'])

In [56]:
s5

,id,age,hypertension,heart_disease,avg_glucose_level,stroke,bmi_m,gender_Female,gender_Male,gender_Other,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67.00,0,1,228.69,1,36.600000,0,1,0,...,0,1,0,0,0,1,0,1,0,0
1,51676,61.00,0,0,202.21,1,28.893237,1,0,0,...,0,0,1,0,1,0,0,0,1,0
2,31112,80.00,0,1,105.92,1,32.500000,0,1,0,...,0,1,0,0,1,0,0,0,1,0
3,60182,49.00,0,0,171.23,1,34.400000,1,0,0,...,0,1,0,0,0,1,0,0,0,1
4,1665,79.00,1,0,174.12,1,24.000000,1,0,0,...,0,0,1,0,1,0,0,0,1,0
5,56669,81.00,0,0,186.21,1,29.000000,0,1,0,...,0,1,0,0,0,1,0,1,0,0
6,53882,74.00,1,1,70.09,1,27.400000,0,1,0,...,0,1,0,0,1,0,0,0,1,0
7,10434,69.00,0,0,94.39,1,22.800000,1,0,0,...,0,1,0,0,0,1,0,0,1,0
8,27419,59.00,0,0,76.15,1,28.893237,1,0,0,...,0,1,0,0,1,0,1,0,0,0
9,60491,78.00,0,0,58.57,1,24.200000,1,0,0,...,0,1,0,0,0,1,1,0,0,0
10,12109,81.00,1,0,80.43,1,29.700000,1,0,0,...,0,1,0,0,1,0,0,0,1,0
11,12095,61.00,0,1,120.46,1,36.800000,1,0,0,...,0,0,0,0,1,0,0,0,0,1
12,12175,54.00,0,0,104.51,1,27.300000,1,0,0,...,0,1,0,0,0,1,0,0,0,1
13,8213,78.00,0,1,219.84,1,28.893237,0,1,0,...,0,1,0,0,0,1,1,0,0,0
14,5317,79.00,0,1,214.09,1,28.200000,1,0,0,...,0,1,0,0,0,1,0,0,1,0
15,58202,50.00,1,0,167.41,1,30.900000,1,0,0,...,0,0,1,0,1,0,0,0,1,0
16,56112,64.00,0,1,191.61,1,37.500000,0,1,0,...,0,1,0,0,0,1,0,0,0,1
17,34120,75.00,1,0,221.29,1,25.800000,0,1,0,...,0,1,0,0,0,1,0,0,0,1
18,27458,60.00,0,0,89.22,1,37.800000,1,0,0,...,0,1,0,0,0,1,0,0,1,0
19,25226,57.00,0,1,217.08,1,28.893237,0,1,0,...,0,0,0,0,0,1,1,0,0,0
20,70630,71.00,0,0,193.94,1,22.400000,1,0,0,...,0,0,0,0,1,0,0,0,0,1
21,13861,52.00,1,0,233.29,1,48.900000,1,0,0,...,0,0,1,0,0,1,0,0,1,0
22,68794,79.00,0,0,228.70,1,26.600000,1,0,0,...,0,0,1,0,0,1,0,0,1,0
23,64778,82.00,0,1,208.30,1,32.500000,0,1,0,...,0,1,0,0,1,0,1,0,0,0
24,4219,71.00,0,0,102.87,1,27.200000,0,1,0,...,0,1,0,0,0,1,0,1,0,0
25,70822,80.00,0,0,104.12,1,23.500000,0,1,0,...,0,0,1,0,1,0,0,0,1,0
26,38047,65.00,0,0,100.98,1,28.200000,1,0,0,...,0,1,0,0,1,0,0,1,0,0
27,61843,58.00,0,0,189.84,1,28.893237,0,1,0,...,0,1,0,0,1,0,1,0,0,0
28,54827,69.00,0,1,195.23,1,28.300000,0,1,0,...,0,0,1,0,0,1,0,0,0,1
29,69160,59.00,0,0,211.78,1,28.893237,0,1,0,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,29.00,0,0,90.52,0,28.000000,1,0,0,...,0,0,1,0,0,1,0,0,1,0
5081,37680,55.00,0,0,108.35,0,40.800000,0,1,0,...,0,0,0,0,1,0,0,1,0,0
5082,24552,44.00,0,0,72.03,0,37.500000,1,0,0,...,0,1,0,0,1,0,0,0,0,1
5083,72914,19.00,0,0,90.57,0,24.200000,1,0,0,...,0,1,0,0,0,1,1,0,0,0
5084,29540,67.00,0,0,97.04,0,26.900000,0,1,0,...,0,1,0,0,1,0,0,0,0,1
5085,53525,72.00,0,0,83.89,0,33.100000,1,0,0,...,0,1,0,0,0,1,0,1,0,0
5086,65411,51.00,0,0,152.56,0,21.800000,1,0,0,...,0,1,0,0,0,1,1,0,0,0
5087,26214,63.00,0,0,75.93,0,34.700000,1,0,0,...,0,0,1,0,1,0,0,1,0,0
5088,22190,64.00,1,0,76.89,0,30.200000,1,0,0,...,0,0,1,0,0,1,1,0,0,0
5089,56714,0.72,0,0,62.13,0,16.800000,1,0,0,...,0,0,0,1,1,0,1,0,0,0
5090,4211,26.00,0,0,100.85,0,21.000000,0,1,0,...,0,0,0,0,1,0,0,0,0,1
5091,6369,59.00,1,0,95.05,0,30.900000,0,1,0,...,0,1,0,0,1,0,0,0,1,0
5092,56799,76.00,0,0,82.35,0,38.900000,0,1,0,...,0,0,0,0,0,1,0,0,1,0
5093,32235,45.00,1,0,95.02,0,28.893237,1,0,0,...,0,0,0,0,1,0,0,0,0,1
5094,28048,13.00,0,0,82.38,0,24.300000,0,1,0,...,0,0,0,1,0,1,1,0,0,0
5095,68598,1.08,0,0,79.15,0,17.400000,0,1,0,...,0,0,0,1,1,0,1,0,0,0
5096,41512,57.00,0,0,76.62,0,28.200000,0,1,0,...,0,0,0,0,1,0,0,0,1,0
5097,64520,68.00,0,0,91.68,0,40.800000,0,1,0,...,0,0,1,0,0,1,1,0,0,0
5098,579,9.00,0,0,71.88,0,17.500000,0,1,0,...,0,0,0,1,0,1,1,0,0,0
5099,7293,40.00,0,0,83.94,0,28.893237,0,1,0,...,0,1,0,0,1,0,0,0,0,1
5100,68398,82.00,1,0,71.97,0,28.300000,0,1,0,...,0,0,1,0,1,0,0,0,1,0
5101,36901,45.00,0,0,97.95,0,24.500000,1,0,0,...,0,1,0,0,0,1,1,0,0,0
5102,45010,57.00,0,0,77.93,0,21.700000,1,0,0,...,0,1,0,0,1,0,0,0,1,0
5103,22127,18.00,0,0,82.85,0,46.900000,1,0,0,...,0,1,0,0,0,1,1,0,0,0
5104,14180,13.00,0,0,103.08,0,18.600000,1,0,0,...,0,0,0,1,1,0,1,0,0,0
5105,18234,80.00,1,0,83.75,0,28.893237,1,0,0,...,0,1,0,0,0,1,0,0,1,0
5106,44873,81.00,0,0,125.20,0,40.000000,1,0,0,...,0,0,1,0,0,1,0,0,1,0
5107,19723,35.00,0,0,82.99,0,30.600000,1,0,0,...,0,0,1,0,1,0,0,0,1,0
5108,37544,51.00,0,0,166.29,0,25.600000,0,1,0,...,0,1,0,0,1,0,0,1,0,0
5109,44679,44.00,0,0,85.28,0,26.200000,1,0,0,...,0,0,0,0,0,1,1,0,0,0

In [60]:
from sklearn.cluster import AgglomerativeClustering

In [61]:
Clst=AgglomerativeClustering(n_clusters=3)

In [62]:
y=s5.stroke

In [63]:
x=s5.drop('stroke',axis=1)

In [64]:
x

,id,age,hypertension,heart_disease,avg_glucose_level,bmi_m,gender_Female,gender_Male,gender_Other,ever_married_No,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67.00,0,1,228.69,36.600000,0,1,0,0,...,0,1,0,0,0,1,0,1,0,0
1,51676,61.00,0,0,202.21,28.893237,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
2,31112,80.00,0,1,105.92,32.500000,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
3,60182,49.00,0,0,171.23,34.400000,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
4,1665,79.00,1,0,174.12,24.000000,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
5,56669,81.00,0,0,186.21,29.000000,0,1,0,0,...,0,1,0,0,0,1,0,1,0,0
6,53882,74.00,1,1,70.09,27.400000,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
7,10434,69.00,0,0,94.39,22.800000,1,0,0,1,...,0,1,0,0,0,1,0,0,1,0
8,27419,59.00,0,0,76.15,28.893237,1,0,0,0,...,0,1,0,0,1,0,1,0,0,0
9,60491,78.00,0,0,58.57,24.200000,1,0,0,0,...,0,1,0,0,0,1,1,0,0,0
10,12109,81.00,1,0,80.43,29.700000,1,0,0,0,...,0,1,0,0,1,0,0,0,1,0
11,12095,61.00,0,1,120.46,36.800000,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
12,12175,54.00,0,0,104.51,27.300000,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
13,8213,78.00,0,1,219.84,28.893237,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
14,5317,79.00,0,1,214.09,28.200000,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0
15,58202,50.00,1,0,167.41,30.900000,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
16,56112,64.00,0,1,191.61,37.500000,0,1,0,0,...,0,1,0,0,0,1,0,0,0,1
17,34120,75.00,1,0,221.29,25.800000,0,1,0,0,...,0,1,0,0,0,1,0,0,0,1
18,27458,60.00,0,0,89.22,37.800000,1,0,0,1,...,0,1,0,0,0,1,0,0,1,0
19,25226,57.00,0,1,217.08,28.893237,0,1,0,1,...,0,0,0,0,0,1,1,0,0,0
20,70630,71.00,0,0,193.94,22.400000,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
21,13861,52.00,1,0,233.29,48.900000,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
22,68794,79.00,0,0,228.70,26.600000,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
23,64778,82.00,0,1,208.30,32.500000,0,1,0,0,...,0,1,0,0,1,0,1,0,0,0
24,4219,71.00,0,0,102.87,27.200000,0,1,0,0,...,0,1,0,0,0,1,0,1,0,0
25,70822,80.00,0,0,104.12,23.500000,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
26,38047,65.00,0,0,100.98,28.200000,1,0,0,0,...,0,1,0,0,1,0,0,1,0,0
27,61843,58.00,0,0,189.84,28.893237,0,1,0,0,...,0,1,0,0,1,0,1,0,0,0
28,54827,69.00,0,1,195.23,28.300000,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
29,69160,59.00,0,0,211.78,28.893237,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,29.00,0,0,90.52,28.000000,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
5081,37680,55.00,0,0,108.35,40.800000,0,1,0,0,...,0,0,0,0,1,0,0,1,0,0
5082,24552,44.00,0,0,72.03,37.500000,1,0,0,0,...,0,1,0,0,1,0,0,0,0,1
5083,72914,19.00,0,0,90.57,24.200000,1,0,0,1,...,0,1,0,0,0,1,1,0,0,0
5084,29540,67.00,0,0,97.04,26.900000,0,1,0,0,...,0,1,0,0,1,0,0,0,0,1
5085,53525,72.00,0,0,83.89,33.100000,1,0,0,0,...,0,1,0,0,0,1,0,1,0,0
5086,65411,51.00,0,0,152.56,21.800000,1,0,0,0,...,0,1,0,0,0,1,1,0,0,0
5087,26214,63.00,0,0,75.93,34.700000,1,0,0,0,...,0,0,1,0,1,0,0,1,0,0
5088,22190,64.00,1,0,76.89,30.200000,1,0,0,0,...,0,0,1,0,0,1,1,0,0,0
5089,56714,0.72,0,0,62.13,16.800000,1,0,0,1,...,0,0,0,1,1,0,1,0,0,0
5090,4211,26.00,0,0,100.85,21.000000,0,1,0,1,...,0,0,0,0,1,0,0,0,0,1
5091,6369,59.00,1,0,95.05,30.900000,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
5092,56799,76.00,0,0,82.35,38.900000,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
5093,32235,45.00,1,0,95.02,28.893237,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
5094,28048,13.00,0,0,82.38,24.300000,0,1,0,1,...,0,0,0,1,0,1,1,0,0,0
5095,68598,1.08,0,0,79.15,17.400000,0,1,0,1,...,0,0,0,1,1,0,1,0,0,0
5096,41512,57.00,0,0,76.62,28.200000,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5097,64520,68.00,0,0,91.68,40.800000,0,1,0,0,...,0,0,1,0,0,1,1,0,0,0
5098,579,9.00,0,0,71.88,17.500000,0,1,0,1,...,0,0,0,1,0,1,1,0,0,0
5099,7293,40.00,0,0,83.94,28.893237,0,1,0,0,...,0,1,0,0,1,0,0,0,0,1
5100,68398,82.00,1,0,71.97,28.300000,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
5101,36901,45.00,0,0,97.95,24.500000,1,0,0,0,...,0,1,0,0,0,1,1,0,0,0
5102,45010,57.00,0,0,77.93,21.700000,1,0,0,0,...,0,1,0,0,1,0,0,0,1,0
5103,22127,18.00,0,0,82.85,46.900000,1,0,0,1,...,0,1,0,0,0,1,1,0,0,0
5104,14180,13.00,0,0,103.08,18.600000,1,0,0,1,...,0,0,0,1,1,0,1,0,0,0
5105,18234,80.00,1,0,83.75,28.893237,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0
5106,44873,81.00,0,0,125.20,40.000000,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
5107,19723,35.00,0,0,82.99,30.600000,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
5108,37544,51.00,0,0,166.29,25.600000,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
5109,44679,44.00,0,0,85.28,26.200000,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0